### ISSUE TITLE
Escaping user input

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#10]
_Please escape all user input fields for special characters before the data travels through the API._

A known issue, already fixed for the BackendConnection-accessURL, but affects pretty much all possible user input. Could be a cause of many problems.

A minor example:

1. ConfigManager-UI: Adding Offered Resource with a `&` in the Description:
![image](https://user-images.githubusercontent.com/75306992/110129171-efcbb200-7dc7-11eb-9c12-0aa5adf2f6a7.png)

2. ConfigManager-UI: As already known, the part from starting at the & is not passed to the ConfigManager
![image](https://user-images.githubusercontent.com/75306992/110129330-20abe700-7dc8-11eb-9a15-22fa6b7a2299.png)

Problem could occur in all user input fields and lead to problems similar to BackendConnection-accessURL, also with other characters. For example, could also lead to problems in the connector configuration settings interface.

**Comment by BastianWel** [comment]
implemented in commit 99d723b
