### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by ctoscano-eu** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#11]
Installed the software. Runned mvn clean packaget. 
Creation of beans failed:
UnsatisfiedDependencyException: Error creating bean with name 'appRouteService' defined in file [D:\soft-dev\eclipse\wspace-for-ids\dataspace-connector\IDS-ConfigurationManager\target\classes\de\fraunhofer\isst\configmanager\configmanagement\service\AppRouteService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configModelService' defined in file [D:\soft-dev\eclipse\wspace-for-ids\dataspace-connector\IDS-ConfigurationManager\target\classes\de\fraunhofer\isst\configmanager\configmanagement\service\ConfigModelService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.fraunhofer.isst.configmanager.configmanagement.service.ConfigModelService]: Constructor threw exception; nested exception is java.lang.NullPointerException

**Comment by tmberthold** [comment]
Hello and thank you for the feedback.

Could you maybe give us the information which version of the ConfigManager you used or which branch was used to create the Maven package?

**Comment by ctoscano-eu** [comment]
Dear TIm
I have used the branch master. After I did mvn clean package and some of the tests failed
Best regards
César

**Comment by tmberthold** [comment]
Hello and thank you for the feedback!
We will take a closer look at the problem and try to recreate it.

**Comment by ctoscano-eu** [comment]
Dear Tim
The log of the tests goes in the annex.
César

**Comment by BastianWel** [comment]
@tmberthold 
Can you transfer this issue to IDS-ConfigurationManager repo?
I am not able to tranfer it.

**Comment by ctoscano-eu** [comment]
Created issue "Tests fail on master branch #52" on the IDS-ConfigurationManager . I will close this issue.
