### ISSUE TITLE
createResourceIdsEndpointAndAddSubRoute

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#19]
Routes:
There is a JS-Function called saveRouteSteps which can call dataUtils.createResourceIdsEndpointAndAddSubRoute within AddRoutePage.js, which gets a lot of Node-Details, but if you look at the called createResourceIdsEndpointAndAddSubRoute within the called dataUtils, the called method tries to add a new resource (??), a new contract and a new representation, which can cause the follwing error, when a route is trying to be saved:

![image](https://user-images.githubusercontent.com/75306992/111672192-020f0c80-881a-11eb-85b9-8db60e69aa89.png)

**Comment by BastianWel** [comment]
This function is used at Data Offering > Routes > Add Route to save an "IDS Endpoint" node (with all resource data).
It should not be possible to add this "IDS Endpoint" node without filling out all the data.
How did you get this call with all this data undefined?

**Comment by BastianWel** [comment]
Incorrect routes are now prevented by client-side validation (commit 4fe2483)
