### ISSUE TITLE
Endless loading after creating a backend-connection during resource-creation

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#21]
When I try to create a resource in my local test environment via the GUI and arrive at the backend-connection and create it there, the green waiting circle does not go away after successful creation, although all information has successfully flowed in the background between GUI and CM. The new backend connection has already been created in the GUI in the background (see screenshot), only the waiting circle should be closed and the rest of the GUI should be released again.

Meanwhile, a JS error message was thrown in the browser console.

![image](https://user-images.githubusercontent.com/75306992/111865068-16abeb80-8965-11eb-9c57-7863d073c968.png)

_Branch: demo_

**Comment by BastianWel** [comment]
Fixed in commit 232f794
