### ISSUE TITLE
Source-Type vs Representation-Type

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#22]
Hello all,
if I should have an error in my logical thinking (it's Saturday), please just close the issue again, but I just have the impression that in the Representation-Tab and in general under the term "Source Type" a wrong logic is implemented or understood at the moment.

When I look at a representation of a resource in the DSC (see screenshot), I get general data, like what format the data has (**type**) and what size, but also information where to find the file `source`, below it again a "**type**". 

I would now expect the data located under `source` to belong to the backend-connection (highlighted in yellow) and the data details to belong to the resource I am creating (highlighted in green).

Accordingly, at the point of the dropdown when creating a resource in the GUI, I would not expect the selection I currently get, as it is not resource specific, but backend-connection specific.

I would expect at the point of the Representation-tab then, looking at the definition of the DSC, to be able to specify information about the type of data itself (json in the screenshot) and the bytesize, but not the type of access to the backend-connection (belongs directly to the backend-connection).

When creating a backend-connection instead, this would also require a dropdown to be created in the GUI as to whether the backend-connection is accessible via the backend-connection-type http-get, https-get or similar.

If I am right, this could explain some problems in the area that some data is not displayed in the GUI because there is an error in the way of thinking (2 x type). Two different meanings of _type_ in the field of representation.

![image](https://user-images.githubusercontent.com/75306992/111866215-31359300-896c-11eb-8af2-7f2b68142edb.png)

---

![image](https://user-images.githubusercontent.com/75306992/111866511-49a6ad00-896e-11eb-869f-301a7fb21529.png)
_(The selection that is currently in the Representation tab should be here.)_

---

@juliapampus @BastianWel

**Comment by tmberthold** [comment]
This logic would also fit to the "Filter by Type" on resource overview. Currently you would display http-get in the column, but I think "json" or similar should be listed in that column. Else the "Filter by Type" doesn't make that much sense.

![image](https://user-images.githubusercontent.com/75306992/111869055-c2f9cc00-897d-11eb-933c-35cca7fc302c.png)

**Comment by BastianWel** [comment]
Yes, source type is part of the backend connection (generic endpoint), but in the info model the generic endpoint data is part of the resource representation.
Later this will all be done via routes, as far as I know.

**Comment by tmberthold** [comment]
So the source-type dropdown should not be under resource-representation like now but backend-connection instead (generic endpoint) because the source-type belongs to the backend-connection itself (which is than part of the representation). If you put the backend-connection source-type under the "Add backend connection" dialog, the backend-connection source-type would not have to be selected each time again, when editing a resource, because the backend-connection of a resource-representation is already known (which includes the representation-backend-connection source-type).

**Comment by BastianWel** [comment]
I can move the drop down menu once I have an API to set the source type to a generic endpoint.
Currently I can only set it to resource representation.

**Comment by tmberthold** [comment]
Thanks for the feedback, new API param will be added!

**Comment by tmberthold** [comment]
Waiting for: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/63

**Comment by BastianWel** [comment]
I close this issue. Solution is also described in issue #24
