### ISSUE TITLE
Backend should use port above 1024

### ISSUE THREAD

**Issue by DominikPinsel** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#34]
The backend component is currently running on port 80. We suggest using a port above 1024 (e.g. 8083), so that a non root user is able to start the backend.
This would help developers, whose IDE is not running as root, and it would make it possible to run the ConfigurationManager-UI inside a docker container as non-root user, which mitigates potential vulnerabilities.

<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by BastianWel** [comment]
Changed in commit 983be17
