### ISSUE TITLE
Implementations for new Enum API

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#37]
The new Configmanager Enum API will return "originalName" & "displayName" for every enum value.
UI should show displayName in select-boxes and use original name for comparison and set original name in data for Configmanager.

**Comment by BastianWel** [comment]
Implemented in commit 111f379 on branch "enums"

**Comment by tmberthold** [comment]
branch "enums" can be merged into dev, we merged our pull-request into our dev
