### ISSUE TITLE
Settings page does not load the selected deploy method for the routes

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#40]
When the settings page is called, the Deploy section says "Deploy Method" and the pre-set or selected deploy method is not displayed.

The following change should be made for this:

In SettingsPage.js the line 74 must be changed from:
`this.$data.deployMethod = response[0][1].deployMethod;`
to
`                    this.$data.deployMethod = response[0][1].routeDeployMethod;
`

**Comment by BastianWel** [comment]
Fixed in commit 1a45cc1
