### ISSUE TITLE
Add Resource: Language in edit/view of a resource  is not the one been saved

### ISSUE THREAD

**Issue by CarstenWhz** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#42]

**Comment by tmberthold** [comment]
Goes back to the data management of the DSC 4.

Issue-Ticket at CM:
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/2

Codeline in DSC 4:
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/21ac858700628fb421e17c1b88a1393794399163/src/main/java/de/fraunhofer/isst/dataspaceconnector/services/utils/IdsUtils.java#L151
