### ISSUE TITLE
IDS Resources: Duration Policy in (h) in edit mode is poluted with xml-coding (2^^xsd:duration instead of 2) 

### ISSUE THREAD

**Issue by CarstenWhz** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#43]

**Comment by tmberthold** [comment]
Goes back to a bug in the infomodel-classes of version 4.0.5. Should be fixed soon with integration of 4.0.6. 

https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/105

**Comment by tmberthold** [comment]
can be closed due to implementation of infomodel-java-classes 4.0.6
