### ISSUE TITLE
Camel-Integration Branch is needed for same changes

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#44]
Camel routes should be created at configmanager after creating a route.
For this, the implementation to create camel routes needs an adjustment on the UI side.

For this change, create please your **own camel branch** and make the following changes:

In the **dataUtils.js** at the **createConnectorEndpoint** as accessUrl currently the following is done: data_ + Date.now()
(Line 556, 672)

This should please be changed to the following:
    
https://localhost:8080/admin/api/resources/3bc8731a-0d82-4899-a3a6-88ab10f31223/data
 
3bc8731a-0d82-4899-a3a6-88ab10f31223 => This is the UUID of the resource

**Comment by BastianWel** [comment]
Implemented in commit c85219f
