### ISSUE TITLE
Dropdowns are not preset since CM uses InfoModel 4.0.6

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#46]
The CM uses the InfoModel 4.0.6.
Therefore, there have been changes in the enum classes, which have ensured that the dropdowns are no longer preset.

Enums have got the following structure:
AA("https://w3id.org/idsa/code/AA")...

Here is from the UI side the following to do, so that the dropdowns work reasonably again.

In the **ResourceMetadataPage**.js => Line 42:
this.$data.language = resource.language.substring(resource.language.lastIndexOf("/")+1);

This ensures that only then "AA" is preserved and displayed.

The following changes need to be made in **SettingsPage**.js:
this.$data.deployMethod = response[0][1].routeDeployMethod;
var loglevelTmp = configModel.logLevel;
this.$data.logLevel = loglevelTmp.substring(loglevelTmp.lastIndexOf("/") +1);
var connectorStatusTmp = configModel.connectorStatus;
this.$data.connectorStatus = connectorStatusTmp.substring(connectorStatusTmp.lastIndexOf("/")+1);
var connectorDeployModeTmp = configModel.connectorDeployMode;
this.$data.connectorDeployMode = connectorDeployModeTmp.substring(connectorDeployModeTmp.lastIndexOf("/")+1);

**Comment by BastianWel** [comment]
Fixed in commit 1a45cc1
