### ISSUE TITLE
UI loads infinitely on wrong Recipient ID

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#54]
Hi,

with a wrong recipient ID the UI loads infinitely.
Setup: 
- DSC branch 386 on port 8080
- UI branch DSC on port 8082 connected to 8080 backend
- DSC branch 386 on port 8081
- Input on Recipient ID: https://localhost:8081/

[Log_UI.txt](https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/files/6825810/Log_UI.txt)
[Log_DSC.txt](https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/files/6825816/Log_DSC.txt)

Best regards,
Heinrich

**Comment by BastianWel** [comment]
Fixed in c36e6ce
