### ISSUE TITLE
Routes edit do not work

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#56]
Hi,

Routes edit do not work in DSC 5 branch.
Btw. if you only click on the eye, the route window say "Edit Route".

Best regards,
Heinrich

**Comment by BastianWel** [comment]
Showing routes became incorrect because the API endpoint "/api/apps" was removed yesterday in DSC.
Fixed in 5480127
