### ISSUE TITLE
Unregister of a broker fails

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#62]
Unregister of a broker fails. Looks like there is a space between recipient and =https[...]

[1] >>> POST https://localhost:8080/api/ids/connector/unavailable?recipient =https%3A%2F%2Fbroker.ids.isst.fraunhofer.de%2Finfrastructure
[1] >>> DATA:  undefined
[1] Error on POST /api/ids/connector/unavailable {"status":400,"statusText":"","headers":{"x-content-type-options":"nosniff","x-xss-protection":"1; mode=block","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pra
gma":"no-cache","expires":"0","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-frame-options":"DENY","content-type":"application/json","transfer-encoding":"chunked","date":"Mon, 19 Jul 2021 08:47:18 GMT","con
nection":"close"},"config":{"url":"https://localhost:8080/api/ids/connector/unavailable?recipient =https%3A%2F%2Fbroker.ids.isst.fraunhofer.de%2Finfrastructure","method":"post","headers":{"Accept":"application/json, text/plain, *
/*","Content-Type":"application/json","User-Agent":"axios/0.19.0"},"auth":{"username":"admin","password":"password"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":
"X-XSRF-TOKEN","maxContentLength":-1,"httpsAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"maxVersion":"TLSv1.2","minVersion":"TLSv1.2","rejectUnauthorized":false,"path":null},"requests":{}
,"sockets":{"localhost:8080::::::::false::TLSv1.2:TLSv1.2::::::::::":[{"_tlsOptions":{"pipe":false,"secureContext":{"context":{},"singleUse":true},"isServer":false,"requestCert":true,"rejectUnauthorized":false,"session":{"type":"
Buffer","data":[48,130,8,198,2,1,1,2,2,3,3,4,2,192,47,4,32,83,18,153,192,29,57,116,69,67,101,147,233,12,154,107,65,73,220,128,196,
[...]

**Comment by BastianWel** [comment]
Fixed since ab744a7
